
<img align="right" width="125" src="https://www.ou.nl/documents/40554/3255217/Logo_OU.jpg"/>

<br>


<center> <font size ="6" color='red'> AI for Prescriptive Analysis </font></center>
<br> 
<center> <font size ="5" color='red'> Discrete Event Simulation in Python</font></center>
<br>

--------------------------

In [3]:
from Controller import*
mycontroller = Controller()
mytab = mycontroller.GetDashBoard(); milptab = mycontroller.GenerateMILPTab()
tab_set = widgets.Tab([mytab,milptab])
tab_set.set_title(0,'Main');tab_set.set_title(1,'MILP'); tab_set

Start day:  2026-08-01  weekday:  5  day:  Saturday , TimeLimit:  None
Controller: Generating dashboard
Visual Manager: Generating dashboard

Tab(children=(VBox(children=(Label(value='TimeLimit: 57600, Orders: 249'), HBox(children=(Select(description='…

In [2]:
import pandas as pd

location_df = pd.read_csv("LocationData.csv")

for entity in location_df["EntityID"].unique():
    sub_df = location_df[location_df["EntityID"] == entity]
    display(sub_df)
    print("______________________________")

,EntityName,EntityID,Time,LocationName,LocationID
0,Operator 1,4,481,CentralBuffer_Location,0
1,Operator 1,4,482,CentralBuffer_Location,0
3,Operator 1,4,483,BW_(BKW_01)_Location,13
7,Operator 1,4,486,BW_(BKW_01)_Location,13
11,Operator 1,4,488,BW_(BKW_01)_Location,13
17,Operator 1,4,492,BW_(BKW_01)_Location,13
19,Operator 1,4,493,BW_(BKW_01)_Location,13
21,Operator 1,4,494,BW_(BKW_01)_Location,13
23,Operator 1,4,496,BW_(BKW_01)_Location,13
44,Operator 1,4,960,CentralBuffer_Location,0
94,Operator 1,4,1921,CentralBuffer_Location,0
95,Operator 1,4,1922,BW_(BKW_01)_Location,13
99,Operator 1,4,2400,CentralBuffer_Location,0
127,Operator 1,4,6241,CentralBuffer_Location,0
128,Operator 1,4,6242,PACK_(VERP_P)_Location,14
130,Operator 1,4,6244,PACK_(VERP_P)_Location,14
132,Operator 1,4,6245,CentralBuffer_Location,0
134,Operator 1,4,6246,PACK_(VERP_P)_Location,14
135,Operator 1,4,6247,PACK_(VERP_P)_Location,14
136,Operator 1,4,6248,CentralBuffer_Location,0
138,Operator 1,4,12343,CentralBuffer_Location,0
139,Operator 1,4,12344,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
140,Operator 1,4,12346,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
141,Operator 1,4,12347,CentralBuffer_Location,0
142,Operator 1,4,12348,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
143,Operator 1,4,12349,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
144,Operator 1,4,12350,PACK_(VERP_P)_Location,14
145,Operator 1,4,12352,PACK_(VERP_P)_Location,14
146,Operator 1,4,12354,PACK_(VERP_P)_Location,14
147,Operator 1,4,12403,PACK_(VERP_P)_Location,14
148,Operator 1,4,12405,PACK_(VERP_P)_Location,14
149,Operator 1,4,12406,PACK_(VERP_P)_Location,14
150,Operator 1,4,12407,CentralBuffer_Location,0
151,Operator 1,4,39640,CentralBuffer_Location,0
152,Operator 1,4,39641,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
153,Operator 1,4,39643,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
154,Operator 1,4,39644,CentralBuffer_Location,0
155,Operator 1,4,39645,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
156,Operator 1,4,39646,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
157,Operator 1,4,39647,CentralBuffer_Location,0
158,Operator 1,4,39734,CentralBuffer_Location,0
159,Operator 1,4,39735,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
160,Operator 1,4,39737,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
161,Operator 1,4,39738,CentralBuffer_Location,0
162,Operator 1,4,39739,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
163,Operator 1,4,39740,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
164,Operator 1,4,39741,PACK_(VERP_P)_Location,14
165,Operator 1,4,39743,PACK_(VERP_P)_Location,14
166,Operator 1,4,39745,PACK_(VERP_P)_Location,14
167,Operator 1,4,39824,PACK_(VERP_P)_Location,14
168,Operator 1,4,39826,PACK_(VERP_P)_Location,14
169,Operator 1,4,39827,PACK_(VERP_P)_Location,14
170,Operator 1,4,39828,CentralBuffer_Location,0

______________________________

,EntityName,EntityID,Time,LocationName,LocationID
2,Operator 2,5,483,CentralBuffer_Location,0
4,Operator 2,5,484,CentralBuffer_Location,0
6,Operator 2,5,485,BW_(BKW_01)_Location,13
13,Operator 2,5,489,BW_(BKW_01)_Location,13
15,Operator 2,5,490,CentralBuffer_Location,0
16,Operator 2,5,491,CentralBuffer_Location,0
18,Operator 2,5,492,UMC750_(M5-03)_Location,8
20,Operator 2,5,494,UMC750_(M5-03)_Location,8
22,Operator 2,5,495,UMC750_(M5-03)_Location,8
24,Operator 2,5,496,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
45,Operator 2,5,960,CentralBuffer_Location,0
96,Operator 2,5,1923,CentralBuffer_Location,0
97,Operator 2,5,1924,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
98,Operator 2,5,1926,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
100,Operator 2,5,2400,CentralBuffer_Location,0
129,Operator 2,5,6243,CentralBuffer_Location,0
131,Operator 2,5,6244,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
133,Operator 2,5,6246,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
137,Operator 2,5,6720,CentralBuffer_Location,0

______________________________

,EntityName,EntityID,Time,LocationName,LocationID
5,Manual worker 1,7,485,CentralBuffer_Location,0
8,Manual worker 1,7,486,CentralBuffer_Location,0
10,Manual worker 1,7,487,VF2SS_(M3-03)_Location,5
25,Manual worker 1,7,519,VF2SS_(M3-03)_Location,5
26,Manual worker 1,7,521,VF2SS_(M3-03)_Location,5
27,Manual worker 1,7,522,VF2SS_(M3-03)_Location,5
28,Manual worker 1,7,523,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
46,Manual worker 1,7,960,CentralBuffer_Location,0

______________________________

,EntityName,EntityID,Time,LocationName,LocationID
9,Manual worker 2,8,487,CentralBuffer_Location,0
12,Manual worker 2,8,488,CentralBuffer_Location,0
14,Manual worker 2,8,489,M3-02_(FR3_02)_Location,2
29,Manual worker 2,8,550,M3-02_(FR3_02)_Location,2
30,Manual worker 2,8,552,M3-02_(FR3_02)_Location,2
31,Manual worker 2,8,553,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
32,Manual worker 2,8,555,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
33,Manual worker 2,8,650,VF2SS_(M3-03)_Location,5
34,Manual worker 2,8,652,VF2SS_(M3-03)_Location,5
35,Manual worker 2,8,653,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
36,Manual worker 2,8,655,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
37,Manual worker 2,8,878,M3-02_(FR3_02)_Location,2
38,Manual worker 2,8,880,M3-02_(FR3_02)_Location,2
39,Manual worker 2,8,881,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
40,Manual worker 2,8,883,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
41,Manual worker 2,8,884,BW_(BKW_01)_Location,13
42,Manual worker 2,8,886,BW_(BKW_01)_Location,13
43,Manual worker 2,8,887,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
47,Manual worker 2,8,960,CentralBuffer_Location,0

______________________________

,EntityName,EntityID,Time,LocationName,LocationID
48,Operator 3,6,961,CentralBuffer_Location,0
49,Operator 3,6,962,BW_(BKW_01)_Location,13
50,Operator 3,6,964,BW_(BKW_01)_Location,13
51,Operator 3,6,965,CentralBuffer_Location,0
52,Operator 3,6,966,BW_(BKW_01)_Location,13
...,...,...,...,...,...
122,Operator 3,6,2752,PACK_(VERP_P)_Location,14
123,Operator 3,6,2753,BW_(BKW_01)_Location,13
124,Operator 3,6,2754,BW_(BKW_01)_Location,13
125,Operator 3,6,2755,OUT - Outsourced activity_(OUT - Outsourced)_L...,15
126,Operator 3,6,4320,CentralBuffer_Location,0

______________________________

In [4]:
import pandas as pd

exec_df = pd.read_csv("EventExecutionData.csv")


for batch in exec_df["Items"].unique():
    sub_df = exec_df[exec_df["Items"] == batch]
    display(sub_df)
    print("______________________________")

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
0,Trailer Loading,1,3360-3361,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_60,CentralBuffer_Location,3361,2026-08-03 08:01:00
1,Trailer Transport,3,3361-3362,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_60,Trailer_60,3362,2026-08-03 08:02:00
3,Trailer Unloading,4,3362-3363,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_60,BW_(BKW_01)_Location,3363,2026-08-03 08:03:00
7,Machine Setup,7,3365-3366,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location,3366,2026-08-03 08:06:00
11,Machine Loading,11,3367-3368,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location,3368,2026-08-03 08:08:00
52,Machine Processing,16,3367-3491.0~3494-3495,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,3495,2026-08-03 10:15:00
53,Machine Unloading,17,3494-3495,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location,3495,2026-08-03 10:15:00
56,Trailer Loading,71,3498-3499,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_61,BW_(BKW_01)_Location,3499,2026-08-03 10:19:00
57,Trailer Transport,73,3499-3500,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_61,Trailer_61,3500,2026-08-03 10:20:00
59,Trailer Unloading,75,3500-3501,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_61,PACK_(VERP_P)_Location,3501,2026-08-03 10:21:00
62,Machine Setup,76,3502-3503,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,3503,2026-08-03 10:23:00
63,Machine Loading,79,3504-3505,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,3505,2026-08-03 10:25:00
64,Machine Processing,80,3504-3528.0~3528-3529,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,3529,2026-08-03 10:49:00
65,Machine Unloading,81,3528-3529,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,3529,2026-08-03 10:49:00
66,Trailer Loading,82,3530-3531,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_61,PACK_(VERP_P)_Location,3531,2026-08-03 10:51:00
67,Trailer Transport,83,3531-3532,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_61,Trailer_61,3532,2026-08-03 10:52:00
68,Trailer Unloading,84,3532-3533,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_61,CentralBuffer_Location,3533,2026-08-03 10:53:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
2,Trailer Loading,2,3362-3363,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 2,Trailer_61,CentralBuffer_Location,3363,2026-08-03 08:03:00
4,Trailer Transport,6,3363-3364,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 2,Trailer_61,Trailer_61,3364,2026-08-03 08:04:00
6,Trailer Unloading,8,3364-3365,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 2,Trailer_61,BW_(BKW_01)_Location,3365,2026-08-03 08:05:00
54,Machine Setup,70,3496-3497,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location,3497,2026-08-03 10:17:00
60,Machine Loading,72,3501-3502,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3502,2026-08-03 10:22:00
69,Machine Processing,77,3501-3551.0~3551-3552,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,3552,2026-08-03 11:12:00
70,Machine Unloading,78,3551-3552,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3552,2026-08-03 11:12:00
75,Trailer Loading,86,3556-3557,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_60,BW_(BKW_01)_Location,3557,2026-08-03 11:17:00
76,Trailer Transport,92,3557-3558,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_60,Trailer_60,3558,2026-08-03 11:18:00
77,Trailer Unloading,93,3558-3559,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_60,PACK_(VERP_P)_Location,3559,2026-08-03 11:19:00
78,Machine Setup,94,3560-3561,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,3561,2026-08-03 11:21:00
79,Machine Loading,95,3562-3563,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,3563,2026-08-03 11:23:00
80,Machine Processing,96,3562-3578.0~3578-3579,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,3579,2026-08-03 11:39:00
81,Machine Unloading,97,3578-3579,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,3579,2026-08-03 11:39:00
82,Trailer Loading,98,3580-3581,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_60,PACK_(VERP_P)_Location,3581,2026-08-03 11:41:00
83,Trailer Transport,99,3581-3582,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_60,Trailer_60,3582,2026-08-03 11:42:00
84,Trailer Unloading,100,3582-3583,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_60,CentralBuffer_Location,3583,2026-08-03 11:43:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
5,Trailer Loading,5,3364-3365,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,Trailer_62,CentralBuffer_Location,3365,2026-08-03 08:05:00
8,Trailer Transport,10,3365-3366,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,Trailer_62,Trailer_62,3366,2026-08-03 08:06:00
10,Trailer Unloading,12,3366-3367,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,Trailer_62,VF2SS_(M3-03)_Location,3367,2026-08-03 08:07:00
38,Machine Setup,15,3369-3399,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,VF2SS_(M3-03),VF2SS_(M3-03)_Location,3399,2026-08-03 08:39:00
55,Machine Loading,50,3404-3499,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,VF2SS_(M3-03),VF2SS_(M3-03)_Location,3499,2026-08-03 10:19:00
108,Machine Processing,60,3404-3840~3842-3946.0~3947-4042,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,VF2SS_(M3-03),VF2SS_(M3-03),VF2SS_(M3-03)_Location,4042,2026-08-03 19:22:00
109,Machine Unloading,127,3947-4042,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,VF2SS_(M3-03),VF2SS_(M3-03)_Location,4042,2026-08-03 19:22:00
115,Trailer Loading,130,4146-4147,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,VF2SS_(M3-03)_Location,4147,2026-08-03 21:07:00
116,Trailer Transport,135,4147-4148,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,Trailer_60,4148,2026-08-03 21:08:00
117,Trailer Unloading,136,4148-4149,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,BW_(BKW_01)_Location,4149,2026-08-03 21:09:00
125,Machine Setup,137,4158-4159,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,4159,2026-08-03 21:19:00
134,Machine Loading,144,4170-4171,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,4171,2026-08-03 21:31:00
149,Machine Processing,153,4170-4320~4801-5225.0~5226-5227,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,5227,2026-08-04 15:07:00
150,Machine Unloading,168,5226-5227,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,BW_(BKW_01),BW_(BKW_01)_Location,5227,2026-08-04 15:07:00
153,Trailer Loading,176,5230-5231,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,Trailer_60,BW_(BKW_01)_Location,5231,2026-08-04 15:11:00
154,Trailer Transport,179,5231-5232,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,Trailer_60,Trailer_60,5232,2026-08-04 15:12:00
155,Trailer Unloading,180,5232-5233,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,Trailer_60,PACK_(VERP_P)_Location,5233,2026-08-04 15:13:00
156,Machine Setup,181,5234-5235,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,PACK_(VERP_P),PACK_(VERP_P)_Location,5235,2026-08-04 15:15:00
157,Machine Loading,182,5236-5237,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,PACK_(VERP_P),PACK_(VERP_P)_Location,5237,2026-08-04 15:17:00
162,Machine Processing,183,5236-5280~5282-5352.0~5407-5408,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,5408,2026-08-04 18:08:00
163,Machine Unloading,187,5407-5408,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,5408,2026-08-04 18:08:00
170,Trailer Loading,190,5416-5417,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,PACK_(VERP_P)_Location,5417,2026-08-04 18:17:00
171,Trailer Transport,197,5417-5418,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,Trailer_60,5418,2026-08-04 18:18:00
172,Trailer Unloading,198,5418-5419,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,CentralBuffer_Location,5419,2026-08-04 18:19:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
9,Trailer Loading,9,3366-3367,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,Trailer_63,CentralBuffer_Location,3367,2026-08-03 08:07:00
12,Trailer Transport,14,3367-3368,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,Trailer_63,Trailer_63,3368,2026-08-03 08:08:00
14,Trailer Unloading,19,3368-3369,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,Trailer_63,M3-02_(FR3_02)_Location,3369,2026-08-03 08:09:00
48,Machine Setup,20,3370-3430,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,M3-02_(FR3_02),M3-02_(FR3_02)_Location,3430,2026-08-03 09:10:00
93,Machine Loading,63,3431-3654,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,M3-02_(FR3_02),M3-02_(FR3_02)_Location,3654,2026-08-03 12:54:00
159,Machine Processing,64,3431-3840~3841-4320~4800-5179.0~5180-5280~5282...,158~159~160~161~162~163~164~165~166~167~168~16...,M3-02_(FR3_02),M3-02_(FR3_02),M3-02_(FR3_02)_Location,5405,2026-08-04 18:05:00
160,Machine Unloading,166,5180-5280~5282-5405,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,M3-02_(FR3_02),M3-02_(FR3_02)_Location,5405,2026-08-04 18:05:00
166,Trailer Loading,188,5411-5412,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,M3-02_(FR3_02)_Location,5412,2026-08-04 18:12:00
167,Trailer Transport,193,5412-5413,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,Trailer_60,5413,2026-08-04 18:13:00
168,Trailer Unloading,194,5413-5414,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,BW_(BKW_01)_Location,5414,2026-08-04 18:14:00
174,Machine Setup,195,5421-5422,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,5422,2026-08-04 18:22:00
175,Machine Loading,200,5423-5424,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,5424,2026-08-04 18:24:00
176,Machine Processing,201,5423-5522.0~5522-5523,158~159~160~161~162~163~164~165~166~167~168~16...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,5523,2026-08-04 20:03:00
177,Machine Unloading,202,5522-5523,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,5523,2026-08-04 20:03:00
180,Trailer Loading,203,5526-5527,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,BW_(BKW_01)_Location,5527,2026-08-04 20:07:00
181,Trailer Transport,206,5527-5528,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,Trailer_60,5528,2026-08-04 20:08:00
182,Trailer Unloading,207,5528-5529,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,5529,2026-08-04 20:09:00
194,Machine Setup,208,6241-6242,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,6242,2026-08-05 08:02:00
196,Machine Loading,225,6243-6244,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,6244,2026-08-05 08:04:00
237,Machine Processing,227,6243-6720~7680-8160~9120-9600~13441-13920~1488...,158~159~160~161~162~163~164~165~166~167~168~16...,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,15215,2026-08-11 13:35:00
238,Machine Unloading,280,15214-15215,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,15215,2026-08-11 13:35:00
241,Trailer Loading,284,15218-15219,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,15219,2026-08-11 13:39:00
242,Trailer Transport,287,15219-15220,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,Trailer_60,15220,2026-08-11 13:40:00
243,Trailer Unloading,288,15220-15221,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,PACK_(VERP_P)_Location,15221,2026-08-11 13:41:00
244,Machine Setup,289,15222-15223,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,15223,2026-08-11 13:43:00
245,Machine Loading,290,15224-15225,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,15225,2026-08-11 13:45:00
246,Machine Processing,291,15224-15273.0~15273-15274,158~159~160~161~162~163~164~165~166~167~168~16...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,15274,2026-08-11 14:34:00
247,Machine Unloading,292,15273-15274,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,15274,2026-08-11 14:34:00
248,Trailer Loading,293,15275-15276,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,PACK_(VERP_P)_Location,15276,2026-08-11 14:36:00
249,Trailer Transport,294,15276-15277,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,Trailer_60,15277,2026-08-11 14:37:00
250,Trailer Unloading,295,15277-15278,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,CentralBuffer_Location,15278,2026-08-11 14:38:00

______________________________

Empty DataFrame
Columns: [EventName, EventID, ProgressSteps, Items, Resource, Equipment, Location, SimTime, Date]
Index: []

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
15,Trailer Loading,13,3369-3370,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 2,Trailer_64,CentralBuffer_Location,3370,2026-08-03 08:10:00
16,Trailer Transport,22,3370-3371,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 2,Trailer_64,Trailer_64,3371,2026-08-03 08:11:00
18,Trailer Unloading,24,3371-3372,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 2,Trailer_64,UMC750_(M5-03)_Location,3372,2026-08-03 08:12:00
45,Machine Setup,25,3373-3403,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 2,UMC750_(M5-03),UMC750_(M5-03)_Location,3403,2026-08-03 08:43:00
61,Machine Loading,57,3404-3503,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 2,UMC750_(M5-03),UMC750_(M5-03)_Location,3503,2026-08-03 10:23:00
111,Machine Processing,59,3404-3840~3841-3966.0~4044-4143,208~209~210~211~212~213~214~215~216~217~218~21...,UMC750_(M5-03),UMC750_(M5-03),UMC750_(M5-03)_Location,4143,2026-08-03 21:03:00
112,Machine Unloading,124,4044-4143,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,UMC750_(M5-03),UMC750_(M5-03)_Location,4143,2026-08-03 21:03:00
121,Trailer Loading,132,4153-4154,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,Trailer_60,UMC750_(M5-03)_Location,4154,2026-08-03 21:14:00
122,Trailer Transport,140,4154-4155,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,Trailer_60,Trailer_60,4155,2026-08-03 21:15:00
123,Trailer Unloading,141,4155-4156,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,Trailer_60,PACK_(VERP_P)_Location,4156,2026-08-03 21:16:00
132,Machine Setup,142,4167-4168,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,4168,2026-08-03 21:28:00
136,Machine Loading,151,4173-4174,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,4174,2026-08-03 21:34:00
137,Machine Processing,156,4173-4202.0~4202-4203,208~209~210~211~212~213~214~215~216~217~218~21...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,4203,2026-08-03 22:03:00
138,Machine Unloading,157,4202-4203,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,4203,2026-08-03 22:03:00
141,Trailer Loading,158,4206-4207,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,Trailer_60,PACK_(VERP_P)_Location,4207,2026-08-03 22:07:00
142,Trailer Transport,161,4207-4208,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,Trailer_60,Trailer_60,4208,2026-08-03 22:08:00
143,Trailer Unloading,162,4208-4209,208~209~210~211~212~213~214~215~216~217~218~21...,Operator 3,Trailer_60,CentralBuffer_Location,4209,2026-08-03 22:09:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
19,Trailer Loading,21,3372-3373,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,Trailer_60,CentralBuffer_Location,3373,2026-08-03 08:13:00
20,Trailer Transport,27,3373-3374,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,Trailer_60,Trailer_60,3374,2026-08-03 08:14:00
21,Trailer Unloading,28,3374-3375,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,Trailer_60,BW_(BKW_01)_Location,3375,2026-08-03 08:15:00
71,Machine Setup,85,3553-3554,238~239~240~241~242~243~244~245~246~247~248~24...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3554,2026-08-03 11:14:00
73,Machine Loading,89,3555-3556,238~239~240~241~242~243~244~245~246~247~248~24...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3556,2026-08-03 11:16:00
95,Machine Processing,90,3555-3794.0~3794-3795,238~239~240~241~242~243~244~245~246~247~248~24...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,3795,2026-08-03 15:15:00
96,Machine Unloading,91,3794-3795,238~239~240~241~242~243~244~245~246~247~248~24...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3795,2026-08-03 15:15:00
101,Trailer Loading,112,3799-3800,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,Trailer_60,BW_(BKW_01)_Location,3800,2026-08-03 15:20:00
102,Trailer Transport,118,3800-3801,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,Trailer_60,Trailer_60,3801,2026-08-03 15:21:00
103,Trailer Unloading,119,3801-3802,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,3802,2026-08-03 15:22:00
104,Machine Setup,120,3803-3804,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,3804,2026-08-03 15:24:00
106,Machine Loading,121,3805-3806,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,3806,2026-08-03 15:26:00
260,Machine Processing,122,3805-3840~4800-5280~6241-6720~7680-8160~9121-9...,238~239~240~241~242~243~244~245~246~247~248~24...,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,39699,2026-08-28 13:39:00
261,Machine Unloading,339,39698-39699,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,39699,2026-08-28 13:39:00
264,Trailer Loading,341,39702-39703,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,39703,2026-08-28 13:43:00
265,Trailer Transport,344,39703-39704,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,Trailer_60,Trailer_60,39704,2026-08-28 13:44:00
266,Trailer Unloading,345,39704-39705,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,Trailer_60,PACK_(VERP_P)_Location,39705,2026-08-28 13:45:00
267,Machine Setup,346,39706-39707,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,39707,2026-08-28 13:47:00
268,Machine Loading,347,39708-39709,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,39709,2026-08-28 13:49:00
277,Machine Processing,348,39708-39787.0~39787-39788,238~239~240~241~242~243~244~245~246~247~248~24...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,39788,2026-08-28 15:08:00
278,Machine Unloading,349,39787-39788,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,39788,2026-08-28 15:08:00
282,Trailer Loading,357,39791-39792,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,Trailer_60,PACK_(VERP_P)_Location,39792,2026-08-28 15:12:00
283,Trailer Transport,362,39792-39793,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,Trailer_60,Trailer_60,39793,2026-08-28 15:13:00
284,Trailer Unloading,363,39793-39794,238~239~240~241~242~243~244~245~246~247~248~24...,Operator 2,Trailer_60,CentralBuffer_Location,39794,2026-08-28 15:14:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
23,Trailer Loading,26,3377-3378,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,Trailer_60,CentralBuffer_Location,3378,2026-08-03 08:18:00
24,Trailer Transport,31,3378-3379,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,Trailer_60,Trailer_60,3379,2026-08-03 08:19:00
25,Trailer Unloading,32,3379-3380,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,3380,2026-08-03 08:20:00
30,Machine Setup,33,3386-3387,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,3387,2026-08-03 08:27:00
37,Machine Loading,39,3396-3397,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,3397,2026-08-03 08:37:00
252,Machine Processing,46,3396-3840~4800-5280~6240-6720~7680-8160~9120-9...,318~319~320~321~322~323~324~325~326~327~328~32...,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,38317,2026-08-27 14:37:00
253,Machine Unloading,329,38316-38317,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,38317,2026-08-27 14:37:00
256,Trailer Loading,333,38320-38321,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,38321,2026-08-27 14:41:00
257,Trailer Transport,336,38321-38322,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,Trailer_60,Trailer_60,38322,2026-08-27 14:42:00
258,Trailer Unloading,337,38322-38323,318~319~320~321~322~323~324~325~326~327~328~32...,Operator 1,Trailer_60,CentralBuffer_Location,38323,2026-08-27 14:43:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
27,Trailer Loading,30,3382-3383,342~343,Operator 1,Trailer_60,CentralBuffer_Location,3383,2026-08-03 08:23:00
28,Trailer Transport,36,3383-3384,342~343,Operator 1,Trailer_60,Trailer_60,3384,2026-08-03 08:24:00
29,Trailer Unloading,37,3384-3385,342~343,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,3385,2026-08-03 08:25:00
36,Machine Setup,38,3394-3395,342~343,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,3395,2026-08-03 08:35:00
43,Machine Loading,45,3401-3402,342~343,Manual worker 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,3402,2026-08-03 08:42:00
222,Machine Processing,53,3401-3840~4801-5280~6240-6720~7681-8160~9122-9...,342~343,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,9496,2026-08-07 14:16:00
223,Machine Unloading,261,9495-9496,342~343,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,9496,2026-08-07 14:16:00
226,Trailer Loading,263,9499-9500,342~343,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,9500,2026-08-07 14:20:00
227,Trailer Transport,266,9500-9501,342~343,Operator 1,Trailer_60,Trailer_60,9501,2026-08-07 14:21:00
228,Trailer Unloading,267,9501-9502,342~343,Operator 1,Trailer_60,PACK_(VERP_P)_Location,9502,2026-08-07 14:22:00
229,Machine Setup,268,9503-9504,342~343,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,9504,2026-08-07 14:24:00
230,Machine Loading,269,9505-9506,342~343,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,9506,2026-08-07 14:26:00
231,Machine Processing,270,9505-9506.0~9506-9507,342~343,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,9507,2026-08-07 14:27:00
232,Machine Unloading,271,9506-9507,342~343,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,9507,2026-08-07 14:27:00
233,Trailer Loading,272,9508-9509,342~343,Operator 1,Trailer_60,PACK_(VERP_P)_Location,9509,2026-08-07 14:29:00
234,Trailer Transport,273,9509-9510,342~343,Operator 1,Trailer_60,Trailer_60,9510,2026-08-07 14:30:00
235,Trailer Unloading,274,9510-9511,342~343,Operator 1,Trailer_60,CentralBuffer_Location,9511,2026-08-07 14:31:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
32,Trailer Loading,35,3389-3390,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,Trailer_60,CentralBuffer_Location,3390,2026-08-03 08:30:00
33,Trailer Transport,42,3390-3391,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,Trailer_60,Trailer_60,3391,2026-08-03 08:31:00
34,Trailer Unloading,43,3391-3392,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,Trailer_60,BW_(BKW_01)_Location,3392,2026-08-03 08:32:00
97,Machine Setup,111,3796-3797,344~345~346~347~348~349~350~351~352~353~354~35...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3797,2026-08-03 15:17:00
99,Machine Loading,115,3798-3799,344~345~346~347~348~349~350~351~352~353~354~35...,Manual worker 1,BW_(BKW_01),BW_(BKW_01)_Location,3799,2026-08-03 15:19:00
118,Machine Processing,116,3798-3840~3841-4074.0~4150-4151,344~345~346~347~348~349~350~351~352~353~354~35...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,4151,2026-08-03 21:11:00
119,Machine Unloading,126,4150-4151,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,4151,2026-08-03 21:11:00
128,Trailer Loading,138,4162-4163,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,Trailer_60,BW_(BKW_01)_Location,4163,2026-08-03 21:23:00
129,Trailer Transport,147,4163-4164,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,Trailer_60,Trailer_60,4164,2026-08-03 21:24:00
130,Trailer Unloading,148,4164-4165,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,4165,2026-08-03 21:25:00
145,Machine Setup,149,4803-4804,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,4804,2026-08-04 08:04:00
146,Machine Loading,171,4805-4806,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,4806,2026-08-04 08:06:00
270,Machine Processing,172,4805-5280~6242-6720~7682-8160~9120-9600~13440-...,344~345~346~347~348~349~350~351~352~353~354~35...,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,39737,2026-08-28 14:17:00
271,Machine Unloading,338,39736-39737,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...,39737,2026-08-28 14:17:00
274,Trailer Loading,351,39740-39741,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...,39741,2026-08-28 14:21:00
275,Trailer Transport,354,39741-39742,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,Trailer_60,Trailer_60,39742,2026-08-28 14:22:00
276,Trailer Unloading,355,39742-39743,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,Trailer_60,PACK_(VERP_P)_Location,39743,2026-08-28 14:23:00
279,Machine Setup,356,39789-39790,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,39790,2026-08-28 15:10:00
281,Machine Loading,359,39791-39792,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,39792,2026-08-28 15:12:00
286,Machine Processing,360,39791-39840~39841-39883.0~39884-39885,344~345~346~347~348~349~350~351~352~353~354~35...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,39885,2026-08-28 16:45:00
287,Machine Unloading,364,39884-39885,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,39885,2026-08-28 16:45:00
290,Trailer Loading,366,39888-39889,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,Trailer_60,PACK_(VERP_P)_Location,39889,2026-08-28 16:49:00
291,Trailer Transport,369,39889-39890,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,Trailer_60,Trailer_60,39890,2026-08-28 16:50:00
292,Trailer Unloading,370,39890-39891,344~345~346~347~348~349~350~351~352~353~354~35...,Operator 3,Trailer_60,CentralBuffer_Location,39891,2026-08-28 16:51:00

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
42,Trailer Loading,41,3400-3401,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,Trailer_60,CentralBuffer_Location,3401,2026-08-03 08:41:00
44,Trailer Transport,52,3401-3402,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,Trailer_60,Trailer_60,3402,2026-08-03 08:42:00
46,Trailer Unloading,55,3402-3403,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,Trailer_60,M3-01_(FR3_01)_Location,3403,2026-08-03 08:43:00
49,Machine Setup,58,3405-3465,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,M3-01_(FR3_01),M3-01_(FR3_01)_Location,3465,2026-08-03 09:45:00
50,Machine Loading,66,3466-3492,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,M3-01_(FR3_01),M3-01_(FR3_01)_Location,3492,2026-08-03 10:12:00
86,Machine Processing,67,3466-3616.0~3617-3643,436~437~438~439~440~441~442~443~444~445~446~44...,M3-01_(FR3_01),M3-01_(FR3_01),M3-01_(FR3_01)_Location,3643,2026-08-03 12:43:00
87,Machine Unloading,68,3617-3643,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,M3-01_(FR3_01),M3-01_(FR3_01)_Location,3643,2026-08-03 12:43:00
90,Trailer Loading,102,3646-3647,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,Trailer_60,M3-01_(FR3_01)_Location,3647,2026-08-03 12:47:00
91,Trailer Transport,105,3647-3648,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,Trailer_60,Trailer_60,3648,2026-08-03 12:48:00
92,Trailer Unloading,106,3648-3649,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,Trailer_60,M5-02_(FR5_02)_Location,3649,2026-08-03 12:49:00
94,Machine Setup,107,3650-3710,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,M5-02_(FR5_02),M5-02_(FR5_02)_Location,3710,2026-08-03 13:50:00
105,Machine Loading,108,3711-3805,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 1,M5-02_(FR5_02),M5-02_(FR5_02)_Location,3805,2026-08-03 15:25:00
184,Machine Processing,109,3711-3840~3843-4320~4321-4800~4803-5280~5281-5...,436~437~438~439~440~441~442~443~444~445~446~44...,M5-02_(FR5_02),M5-02_(FR5_02),M5-02_(FR5_02)_Location,5616,2026-08-04 21:36:00
185,Machine Unloading,186,5615-5616,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,M5-02_(FR5_02),M5-02_(FR5_02)_Location,5616,2026-08-04 21:36:00
188,Trailer Loading,210,5619-5620,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,M5-02_(FR5_02)_Location,5620,2026-08-04 21:40:00
189,Trailer Transport,213,5620-5621,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,Trailer_60,5621,2026-08-04 21:41:00
190,Trailer Unloading,214,5621-5622,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,M3-01_(FR3_01)_Location,5622,2026-08-04 21:42:00
191,Machine Setup,215,5623-5683,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,M3-01_(FR3_01),M3-01_(FR3_01)_Location,5683,2026-08-04 22:43:00
195,Machine Loading,216,5684-5760~6242-6244,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,M3-01_(FR3_01),M3-01_(FR3_01)_Location,6244,2026-08-05 08:04:00
197,Machine Processing,217,5684-5760~6240-6606.0~6606-6684,436~437~438~439~440~441~442~443~444~445~446~44...,M3-01_(FR3_01),M3-01_(FR3_01),M3-01_(FR3_01)_Location,6684,2026-08-05 15:24:00
198,Machine Unloading,222,6606-6684,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,M3-01_(FR3_01),M3-01_(FR3_01)_Location,6684,2026-08-05 15:24:00
201,Trailer Loading,229,6687-6688,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,Trailer_60,M3-01_(FR3_01)_Location,6688,2026-08-05 15:28:00
202,Trailer Transport,232,6688-6689,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,Trailer_60,Trailer_60,6689,2026-08-05 15:29:00
203,Trailer Unloading,233,6689-6690,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,Trailer_60,BW_(BKW_01)_Location,6690,2026-08-05 15:30:00
204,Machine Setup,234,6691-6692,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,BW_(BKW_01),BW_(BKW_01)_Location,6692,2026-08-05 15:32:00
205,Machine Loading,235,6693-6694,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 2,BW_(BKW_01),BW_(BKW_01)_Location,6694,2026-08-05 15:34:00
207,Machine Processing,236,6693-6720~6721-6865.0~6866-6867,436~437~438~439~440~441~442~443~444~445~446~44...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,6867,2026-08-05 18:27:00
208,Machine Unloading,238,6866-6867,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location,6867,2026-08-05 18:27:00
211,Trailer Loading,240,6870-6871,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,BW_(BKW_01)_Location,6871,2026-08-05 18:31:00
212,Trailer Transport,243,6871-6872,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,Trailer_60,6872,2026-08-05 18:32:00
213,Trailer Unloading,244,6872-6873,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,PACK_(VERP_P)_Location,6873,2026-08-05 18:33:00
214,Machine Setup,245,6874-6875,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,6875,2026-08-05 18:35:00
215,Machine Loading,246,6876-6877,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,6877,2026-08-05 18:37:00
216,Machine Processing,247,6876-6961.0~6961-6962,436~437~438~439~440~441~442~443~444~445~446~44...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,6962,2026-08-05 20:02:00
217,Machine Unloading,248,6961-6962,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,PACK_(VERP_P),PACK_(VERP_P)_Location,6962,2026-08-05 20:02:00
218,Trailer Loading,249,6963-6964,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,PACK_(VERP_P)_Location,6964,2026-08-05 20:04:00
219,Trailer Transport,250,6964-6965,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,Trailer_60,6965,2026-08-05 20:05:00
220,Trailer Unloading,251,6965-6966,436~437~438~439~440~441~442~443~444~445~446~44...,Operator 3,Trailer_60,CentralBuffer_Location,6966,2026-08-05 20:06:00

______________________________

In [6]:
import pandas as pd

exec_df = pd.read_csv("BufferData.csv")

for buff in exec_df["BufferName"].unique():
    sub_df = exec_df[exec_df["BufferName"] == buff]
    display(sub_df)
    print("______________________________")

        BufferName  BufferID            Machine  Time  No.Items
0   Central_Output       NaN  Central Inventory     0        25
1   Central_Output       NaN  Central Inventory     0        25
2   Central_Output       NaN  Central Inventory     0        42
3   Central_Output       NaN  Central Inventory     0        42
4   Central_Output       NaN  Central Inventory     0       157
5   Central_Output       NaN  Central Inventory     0       157
6   Central_Output       NaN  Central Inventory     0       207
7   Central_Output       NaN  Central Inventory     0       207
8   Central_Output       NaN  Central Inventory     0       237
9   Central_Output       NaN  Central Inventory     0       237
10  Central_Output       NaN  Central Inventory     0       317
11  Central_Output       NaN  Central Inventory     0       317
12  Central_Output       NaN  Central Inventory     0       341
13  Central_Output       NaN  Central Inventory     0       341
14  Central_Output       NaN  Central Inventory   481       316
15  Central_Output       NaN  Central Inventory   483       299
17  Central_Output       NaN  Central Inventory   485       184
19  Central_Output       NaN  Central Inventory   487       134
23  Central_Output       NaN  Central Inventory   490       104
24  Central_Output       NaN  Central Inventory   492        24
26  Central_Output       NaN  Central Inventory   494         0

______________________________

           BufferName  BufferID      Machine  Time  No.Items
16  BW_(BKW_01)_Input       NaN  BW_(BKW_01)   483        25
18  BW_(BKW_01)_Input       NaN  BW_(BKW_01)   485        42
21  BW_(BKW_01)_Input       NaN  BW_(BKW_01)   488        17
27  BW_(BKW_01)_Input       NaN  BW_(BKW_01)   494        97
33  BW_(BKW_01)_Input       NaN  BW_(BKW_01)   619        80
42  BW_(BKW_01)_Input       NaN  BW_(BKW_01)   673         0
55  BW_(BKW_01)_Input       NaN  BW_(BKW_01)  1262       115
58  BW_(BKW_01)_Input       NaN  BW_(BKW_01)  1275         0
70  BW_(BKW_01)_Input       NaN  BW_(BKW_01)  2534        50
73  BW_(BKW_01)_Input       NaN  BW_(BKW_01)  2543         0

______________________________

             BufferName  BufferID        Machine  Time  No.Items
20  VF2SS_(M3-03)_Input       NaN  VF2SS_(M3-03)   487       115
31  VF2SS_(M3-03)_Input       NaN  VF2SS_(M3-03)   615         0

______________________________

              BufferName  BufferID         Machine  Time  No.Items
22  M3-02_(FR3_02)_Input       NaN  M3-02_(FR3_02)   489        50
48  M3-02_(FR3_02)_Input       NaN  M3-02_(FR3_02)   774         0

______________________________

              BufferName  BufferID         Machine  Time  No.Items
25  UMC750_(M5-03)_Input       NaN  UMC750_(M5-03)   492        30
36  UMC750_(M5-03)_Input       NaN  UMC750_(M5-03)   626         0

______________________________

,BufferName,BufferID,Machine,Time,No.Items
28,OUT - Outsourced activity_(OUT - Outsourced)_I...,NaN,OUT - Outsourced activity_(OUT - Outsourced),496,24
29,OUT - Outsourced activity_(OUT - Outsourced)_I...,NaN,OUT - Outsourced activity_(OUT - Outsourced),500,0
51,OUT - Outsourced activity_(OUT - Outsourced)_I...,NaN,OUT - Outsourced activity_(OUT - Outsourced),918,80
76,OUT - Outsourced activity_(OUT - Outsourced)_I...,NaN,OUT - Outsourced activity_(OUT - Outsourced),2648,130
79,OUT - Outsourced activity_(OUT - Outsourced)_I...,NaN,OUT - Outsourced activity_(OUT - Outsourced),38304,80
83,OUT - Outsourced activity_(OUT - Outsourced)_I...,NaN,OUT - Outsourced activity_(OUT - Outsourced),48238,0

______________________________

            BufferName  BufferID      Machine  Time  No.Items
30  BW_(BKW_01)_Output       NaN  BW_(BKW_01)   613        25
32  BW_(BKW_01)_Output       NaN  BW_(BKW_01)   617         0
40  BW_(BKW_01)_Output       NaN  BW_(BKW_01)   669        17
41  BW_(BKW_01)_Output       NaN  BW_(BKW_01)   672         0
49  BW_(BKW_01)_Output       NaN  BW_(BKW_01)   912        80
50  BW_(BKW_01)_Output       NaN  BW_(BKW_01)   916         0
63  BW_(BKW_01)_Output       NaN  BW_(BKW_01)  2330       115
64  BW_(BKW_01)_Output       NaN  BW_(BKW_01)  2334         0
74  BW_(BKW_01)_Output       NaN  BW_(BKW_01)  2642        50
75  BW_(BKW_01)_Output       NaN  BW_(BKW_01)  2646         0

______________________________

             BufferName  BufferID        Machine   Time  No.Items
34  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)    619        25
35  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)    623         0
43  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)    674        17
44  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)    678         0
57  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)   1266        30
59  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)   1278         0
65  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)   2336       115
66  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)   2340         0
84  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)  48239        50
85  PACK_(VERP_P)_Input       NaN  PACK_(VERP_P)  48243         0

______________________________

              BufferName  BufferID        Machine   Time  No.Items
37  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)    647        25
38  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)    649         0
45  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)    694        17
46  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)    696         0
60  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)   1307        30
61  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)   1309         0
68  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)   2530       115
71  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)   2536         0
86  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)  48292        50
87  PACK_(VERP_P)_Output       NaN  PACK_(VERP_P)  48294         0

______________________________

       BufferName  BufferID            Machine   Time  No.Items
39  Central_Input       NaN  Central Inventory    651        25
47  Central_Input       NaN  Central Inventory    698        42
62  Central_Input       NaN  Central Inventory   1311        72
72  Central_Input       NaN  Central Inventory   2538       187
80  Central_Input       NaN  Central Inventory  38305       211
88  Central_Input       NaN  Central Inventory  48296       261

______________________________

              BufferName  BufferID        Machine  Time  No.Items
52  VF2SS_(M3-03)_Output       NaN  VF2SS_(M3-03)  1157       115
54  VF2SS_(M3-03)_Output       NaN  VF2SS_(M3-03)  1260         0

______________________________

               BufferName  BufferID         Machine  Time  No.Items
53  UMC750_(M5-03)_Output       NaN  UMC750_(M5-03)  1258        30
56  UMC750_(M5-03)_Output       NaN  UMC750_(M5-03)  1264         0

______________________________

               BufferName  BufferID         Machine  Time  No.Items
67  M3-02_(FR3_02)_Output       NaN  M3-02_(FR3_02)  2527        50
69  M3-02_(FR3_02)_Output       NaN  M3-02_(FR3_02)  2532         0

______________________________

,BufferName,BufferID,Machine,Time,No.Items
77,OUT - Outsourced activity_(OUT - Outsourced)_O...,NaN,OUT - Outsourced activity_(OUT - Outsourced),38300,24
78,OUT - Outsourced activity_(OUT - Outsourced)_O...,NaN,OUT - Outsourced activity_(OUT - Outsourced),38303,0
81,OUT - Outsourced activity_(OUT - Outsourced)_O...,NaN,OUT - Outsourced activity_(OUT - Outsourced),48234,50
82,OUT - Outsourced activity_(OUT - Outsourced)_O...,NaN,OUT - Outsourced activity_(OUT - Outsourced),48237,0

______________________________