
<img align="right" width="125" src="https://www.ou.nl/documents/40554/3255217/Logo_OU.jpg"/>

<br>


<center> <font size ="6" color='red'> AI for Prescriptive Analysis </font></center>
<br> 
<center> <font size ="5" color='red'> Discrete Event Simulation in Python</font></center>
<br>

--------------------------

In [1]:
from Controller import*
mycontroller = Controller()
mytab = mycontroller.GetDashBoard(); milptab = mycontroller.GenerateMILPTab()
tab_set = widgets.Tab([mytab,milptab])
tab_set.set_title(0,'Main');tab_set.set_title(1,'MILP'); tab_set

Start day:  2026-07-29  weekday:  2  day:  Wednesday , TimeLimit:  None
Controller: Generating dashboard
Visual Manager: Generating dashboard

Tab(children=(VBox(children=(Label(value='TimeLimit: 57600, Orders: 249'), HBox(children=(Select(description='…

In [2]:
import pandas as pd

location_df = pd.read_csv("LocationData.csv")

for entity in location_df["EntityID"].unique():
    sub_df = location_df[location_df["EntityID"] == entity]
    display(sub_df)
    print("______________________________")

    EntityName  EntityID  Time            LocationName  LocationID
0   Operator 1         4   480  CentralBuffer_Location           0
4   Operator 1         4   481  CentralBuffer_Location           0
5   Operator 1         4   482  CentralBuffer_Location           0
7   Operator 1         4   483    BW_(BKW_01)_Location          13
11  Operator 1         4   486    BW_(BKW_01)_Location          13
14  Operator 1         4   488    BW_(BKW_01)_Location          13
16  Operator 1         4   612    BW_(BKW_01)_Location          13
18  Operator 1         4   614    BW_(BKW_01)_Location          13
20  Operator 1         4   616    BW_(BKW_01)_Location          13
29  Operator 1         4   666    BW_(BKW_01)_Location          13
30  Operator 1         4   668    BW_(BKW_01)_Location          13
31  Operator 1         4   669    BW_(BKW_01)_Location          13
32  Operator 1         4   670  PACK_(VERP_P)_Location          14
33  Operator 1         4   672  PACK_(VERP_P)_Location          14
34  Operator 1         4   674  PACK_(VERP_P)_Location          14
35  Operator 1         4   690  PACK_(VERP_P)_Location          14
36  Operator 1         4   692  PACK_(VERP_P)_Location          14
37  Operator 1         4   693  PACK_(VERP_P)_Location          14
38  Operator 1         4   694  CentralBuffer_Location           0
49  Operator 1         4  1920  CentralBuffer_Location           0
53  Operator 1         4  2220  CentralBuffer_Location           0
54  Operator 1         4  2221    BW_(BKW_01)_Location          13
55  Operator 1         4  2223    BW_(BKW_01)_Location          13
56  Operator 1         4  2224  CentralBuffer_Location           0
57  Operator 1         4  2225    BW_(BKW_01)_Location          13
58  Operator 1         4  2226    BW_(BKW_01)_Location          13
59  Operator 1         4  2227  PACK_(VERP_P)_Location          14
60  Operator 1         4  2229  PACK_(VERP_P)_Location          14
61  Operator 1         4  2231  PACK_(VERP_P)_Location          14
62  Operator 1         4  2345  PACK_(VERP_P)_Location          14
63  Operator 1         4  2347  PACK_(VERP_P)_Location          14
64  Operator 1         4  2348  PACK_(VERP_P)_Location          14
65  Operator 1         4  2349  CentralBuffer_Location           0

______________________________

    EntityName  EntityID  Time            LocationName  LocationID
1   Operator 2         5   480  CentralBuffer_Location           0
6   Operator 2         5   483  CentralBuffer_Location           0
8   Operator 2         5   484  CentralBuffer_Location           0
10  Operator 2         5   485    BW_(BKW_01)_Location          13
19  Operator 2         5   615    BW_(BKW_01)_Location          13
21  Operator 2         5   616    BW_(BKW_01)_Location          13
22  Operator 2         5   617  PACK_(VERP_P)_Location          14
23  Operator 2         5   619  PACK_(VERP_P)_Location          14
24  Operator 2         5   621  PACK_(VERP_P)_Location          14
25  Operator 2         5   645  PACK_(VERP_P)_Location          14
26  Operator 2         5   647  PACK_(VERP_P)_Location          14
27  Operator 2         5   648  PACK_(VERP_P)_Location          14
28  Operator 2         5   649  CentralBuffer_Location           0
50  Operator 2         5  1920  CentralBuffer_Location           0

______________________________

         EntityName  EntityID  Time            LocationName  LocationID
2   Manual worker 1         7   480  CentralBuffer_Location           0
9   Manual worker 1         7   485  CentralBuffer_Location           0
12  Manual worker 1         7   486  CentralBuffer_Location           0
13  Manual worker 1         7   487  VF2SS_(M3-03)_Location           5
15  Manual worker 1         7   518  VF2SS_(M3-03)_Location           5
17  Manual worker 1         7   614  VF2SS_(M3-03)_Location           5
51  Manual worker 1         7  1920  CentralBuffer_Location           0

______________________________

         EntityName  EntityID  Time            LocationName  LocationID
3   Manual worker 2         8   480  CentralBuffer_Location           0
52  Manual worker 2         8  1920  CentralBuffer_Location           0

______________________________

    EntityName  EntityID  Time            LocationName  LocationID
39  Operator 3         6   960  CentralBuffer_Location           0
40  Operator 3         6  1061  CentralBuffer_Location           0
41  Operator 3         6  1156  VF2SS_(M3-03)_Location           5
42  Operator 3         6  1158  VF2SS_(M3-03)_Location           5
43  Operator 3         6  1159  CentralBuffer_Location           0
44  Operator 3         6  1160  VF2SS_(M3-03)_Location           5
45  Operator 3         6  1161  VF2SS_(M3-03)_Location           5
46  Operator 3         6  1162    BW_(BKW_01)_Location          13
47  Operator 3         6  1164    BW_(BKW_01)_Location          13
48  Operator 3         6  1166    BW_(BKW_01)_Location          13

______________________________

In [2]:
import pandas as pd

exec_df = pd.read_csv("EventExecutionData.csv")

for batch in exec_df["Items"].unique():
    sub_df = exec_df[exec_df["Items"] == batch]
    display(sub_df)
    print("______________________________")

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location
0,Trailer Loading,1,480-481,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_60,CentralBuffer_Location
1,Trailer Transport,3,481-482,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_60,Trailer_60
3,Trailer Unloading,4,482-483,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,Trailer_60,BW_(BKW_01)_Location
7,Machine Setup,7,485-486,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
11,Machine Loading,11,487-488,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
16,Machine Processing,15,487-611.0~611-612,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location
17,Machine Unloading,16,611-612,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
20,Trailer Loading,26,614-615,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,Trailer_60,BW_(BKW_01)_Location
22,Trailer Transport,28,615-616,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,Trailer_60,Trailer_60
23,Trailer Unloading,31,616-617,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,Trailer_60,PACK_(VERP_P)_Location
24,Machine Setup,32,618-619,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,PACK_(VERP_P),PACK_(VERP_P)_Location
25,Machine Loading,33,620-621,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,PACK_(VERP_P),PACK_(VERP_P)_Location
26,Machine Processing,34,620-644.0~644-645,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location
27,Machine Unloading,35,644-645,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,PACK_(VERP_P),PACK_(VERP_P)_Location
28,Trailer Loading,36,646-647,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,Trailer_60,PACK_(VERP_P)_Location
29,Trailer Transport,37,647-648,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,Trailer_60,Trailer_60
30,Trailer Unloading,38,648-649,1~2~3~4~5~6~7~8~9~10~11~12~13~14~15~16~17~18~1...,Operator 2,Trailer_60,CentralBuffer_Location

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location
2,Trailer Loading,2,482-483,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 2,Trailer_61,CentralBuffer_Location
4,Trailer Transport,6,483-484,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 2,Trailer_61,Trailer_61
6,Trailer Unloading,8,484-485,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 2,Trailer_61,BW_(BKW_01)_Location
19,Machine Setup,25,613-614,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
21,Machine Loading,27,615-616,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
31,Machine Processing,29,615-665.0~665-666,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location
32,Machine Unloading,30,665-666,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
33,Trailer Loading,39,667-668,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_61,BW_(BKW_01)_Location
34,Trailer Transport,40,668-669,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_61,Trailer_61
35,Trailer Unloading,41,669-670,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_61,PACK_(VERP_P)_Location
36,Machine Setup,42,671-672,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
37,Machine Loading,43,673-674,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
38,Machine Processing,44,673-689.0~689-690,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location
39,Machine Unloading,45,689-690,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
40,Trailer Loading,46,691-692,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_61,PACK_(VERP_P)_Location
41,Trailer Transport,47,692-693,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_61,Trailer_61
42,Trailer Unloading,48,693-694,26~27~28~29~30~31~32~33~34~35~36~37~38~39~40~4...,Operator 1,Trailer_61,CentralBuffer_Location

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location
5,Trailer Loading,5,484-485,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,Trailer_62,CentralBuffer_Location
8,Trailer Transport,10,485-486,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,Trailer_62,Trailer_62
10,Trailer Unloading,12,486-487,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,Trailer_62,VF2SS_(M3-03)_Location
14,Machine Setup,14,488-518,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,VF2SS_(M3-03),VF2SS_(M3-03)_Location
18,Machine Loading,19,519-614,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Manual worker 1,VF2SS_(M3-03),VF2SS_(M3-03)_Location
45,Machine Processing,20,519-960~961-1060.0~1061-1156,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,VF2SS_(M3-03),VF2SS_(M3-03),VF2SS_(M3-03)_Location
46,Machine Unloading,49,1061-1156,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,VF2SS_(M3-03),VF2SS_(M3-03)_Location
49,Trailer Loading,52,1159-1160,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,VF2SS_(M3-03)_Location
50,Trailer Transport,55,1160-1161,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,Trailer_60
51,Trailer Unloading,56,1161-1162,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,Trailer_60,BW_(BKW_01)_Location
52,Machine Setup,57,1163-1164,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location
53,Machine Loading,58,1165-1166,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location
55,Machine Processing,59,1165-1440~1921-2220.0~2221-2222,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location
56,Machine Unloading,62,2221-2222,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location
59,Trailer Loading,64,2225-2226,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 1,Trailer_60,BW_(BKW_01)_Location
60,Trailer Transport,67,2226-2227,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 1,Trailer_60,Trailer_60
61,Trailer Unloading,68,2227-2228,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 1,Trailer_60,PACK_(VERP_P)_Location
62,Machine Setup,69,2229-2230,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
63,Machine Loading,70,2231-2232,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
66,Machine Processing,71,2231-2345.0~2346-2347,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location
67,Machine Unloading,72,2346-2347,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,PACK_(VERP_P),PACK_(VERP_P)_Location
68,Trailer Loading,75,2348-2349,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,Trailer_60,PACK_(VERP_P)_Location
69,Trailer Transport,76,2349-2350,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,Trailer_60,Trailer_60
70,Trailer Unloading,77,2350-2351,43~44~45~46~47~48~49~50~51~52~53~54~55~56~57~5...,Operator 2,Trailer_60,CentralBuffer_Location

______________________________

,EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location
9,Trailer Loading,9,486-487,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,Trailer_63,CentralBuffer_Location
12,Trailer Transport,13,487-488,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,Trailer_63,Trailer_63
13,Trailer Unloading,17,488-489,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,Trailer_63,M3-02_(FR3_02)_Location
15,Machine Setup,18,490-550,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,M3-02_(FR3_02),M3-02_(FR3_02)_Location
43,Machine Loading,22,551-774,158~159~160~161~162~163~164~165~166~167~168~16...,Manual worker 2,M3-02_(FR3_02),M3-02_(FR3_02)_Location
72,Machine Processing,23,551-960~962-1440~1920-2300.0~2301-2400~2403-2527,158~159~160~161~162~163~164~165~166~167~168~16...,M3-02_(FR3_02),M3-02_(FR3_02),M3-02_(FR3_02)_Location
73,Machine Unloading,61,2301-2400~2403-2527,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,M3-02_(FR3_02),M3-02_(FR3_02)_Location
76,Trailer Loading,79,2530-2531,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,M3-02_(FR3_02)_Location
77,Trailer Transport,82,2531-2532,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,Trailer_60
78,Trailer Unloading,83,2532-2533,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,BW_(BKW_01)_Location
79,Machine Setup,84,2534-2535,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location
80,Machine Loading,85,2536-2537,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location
81,Machine Processing,86,2536-2635.0~2635-2636,158~159~160~161~162~163~164~165~166~167~168~16...,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location
82,Machine Unloading,87,2635-2636,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,BW_(BKW_01),BW_(BKW_01)_Location
83,Trailer Loading,88,2637-2638,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,BW_(BKW_01)_Location
84,Trailer Transport,89,2638-2639,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,Trailer_60
85,Trailer Unloading,90,2639-2640,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 3,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...
87,Machine Setup,91,3361-3362,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...
88,Machine Loading,93,3363-3364,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...
90,Machine Processing,94,3363-3840~7680-8160~9120-9600~10560-11040~1200...,158~159~160~161~162~163~164~165~166~167~168~16...,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...
91,Machine Unloading,99,12333-12334,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,OUT - Outsourced activity_(OUT - Outsourced),OUT - Outsourced activity_(OUT - Outsourced)_L...
94,Trailer Loading,101,12337-12338,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,OUT - Outsourced activity_(OUT - Outsourced)_L...
95,Trailer Transport,104,12338-12339,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,Trailer_60
96,Trailer Unloading,105,12339-12340,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,PACK_(VERP_P)_Location
97,Machine Setup,106,12341-12342,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
98,Machine Loading,107,12343-12344,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
99,Machine Processing,108,12343-12392.0~12392-12393,158~159~160~161~162~163~164~165~166~167~168~16...,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location
100,Machine Unloading,109,12392-12393,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location
101,Trailer Loading,110,12394-12395,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,PACK_(VERP_P)_Location
102,Trailer Transport,111,12395-12396,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,Trailer_60
103,Trailer Unloading,112,12396-12397,158~159~160~161~162~163~164~165~166~167~168~16...,Operator 1,Trailer_60,CentralBuffer_Location

______________________________

Empty DataFrame
Columns: [EventName, EventID, ProgressSteps, Items, Resource, Equipment, Location]
Index: []

______________________________