
<img align="right" width="125" src="https://www.ou.nl/documents/40554/3255217/Logo_OU.jpg"/>

<br>


<center> <font size ="6" color='red'> AI for Prescriptive Analysis </font></center>
<br> 
<center> <font size ="5" color='red'> Discrete Event Simulation in Python</font></center>
<br>

--------------------------

In [1]:
from controller import *
mycontroller = Controller()
mytab = mycontroller.GetDashBoard(); tab_set = widgets.Tab([mytab]); tab_set.set_title(0,'Production Planning'); tab_set

Start day:  2026-09-10  weekday:  3  day:  Thursday , TimeLimit:  None
Controller: Generating dashboard
Visual Manager: Generating dashboard

Tab(children=(VBox(children=(Label(value='TimeLimit: 72000, Orders: 249'), HBox(children=(Select(description='…

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

diagnose = True

print("Item batches: "+str(len(exec_df["Items"].unique())))

for batch in exec_df["Items"].unique():
    if pd.isnull(batch):
        continue
    sub_df = exec_df[exec_df["Items"] == batch]
    sub_df = sub_df.sort_values(['SimTime'])
    start = sub_df.iloc[0, sub_df.columns.get_loc('Location')]
    end = sub_df.iloc[len(sub_df)-1, sub_df.columns.get_loc('Location')]

    if batch =="1~17":
        display(sub_df)
    
        print("______________________________")
    

op1_df = exec_df[exec_df["Resource"] == "Operator 1"]


display(op1_df.head(20))

op2_df = exec_df[exec_df["Resource"] == "Operator 2"]


display(op2_df.head(20))

Item batches: 154

,ID,Product,Product/ID,Quantity To Produce,Deadline,Reference,Work Orders/Work Center,Work Orders/Work Center/ID,Processing Machine,Work Orders/Operation,...,Lateness (days),EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,1,[2026-09-10 08:00:00-2026-09-10 08:01:00],1~17,Operator 1,Trailer_60,CentralBuffer_Location,481,2026-09-10 08:01:00
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,154,[2026-09-10 08:01:00-2026-09-10 08:02:00],1~17,Operator 1,Trailer_60,Trailer_60,482,2026-09-10 08:02:00
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,158,[2026-09-10 08:02:00-2026-09-10 08:03:00],1~17,Operator 1,Trailer_60,BW_(BKW_01)_Location,483,2026-09-10 08:03:00
328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Machine Setup,162,[2026-09-10 09:42:00-2026-09-10 09:43:00],1~17,Operator 1,BW_(BKW_01),BW_(BKW_01)_Location,583,2026-09-10 09:43:00
680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Machine Loading,632,[2026-09-10 13:33:00-2026-09-10 13:34:00],1~17,Operator 2,BW_(BKW_01),BW_(BKW_01)_Location,814,2026-09-10 13:34:00
707,__export__.mrp_production_6300_645dbbde,[4022-637-29301] Hinge Block Fixed RM,14964.0,17.0,2026-01-16 10:00:00,TBRM /MO/01266-002,BW - Benchwork (BKW_01),__export__.mrp_workcenter_66_9f807a30,BW_(BKW_01),BW - Benchwork (BKW_01),...,NaN,Machine Processing,1120,[2026-09-10 13:34:00-2026-09-10 14:23:00],1~17,BW_(BKW_01),BW_(BKW_01),BW_(BKW_01)_Location,863,2026-09-10 14:23:00
744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Machine Unloading,1147,[2026-09-11 08:07:00-2026-09-11 08:08:00],1~17,Manual worker 2,BW_(BKW_01),BW_(BKW_01)_Location,1928,2026-09-11 08:08:00
771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,1184,[2026-09-11 10:21:00-2026-09-11 10:22:00],1~17,Manual worker 2,Trailer_60,BW_(BKW_01)_Location,2062,2026-09-11 10:22:00
772,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,1213,[2026-09-11 10:22:00-2026-09-11 10:23:00],1~17,Manual worker 2,Trailer_60,Trailer_60,2063,2026-09-11 10:23:00
773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,1214,[2026-09-11 10:23:00-2026-09-11 10:24:00],1~17,Manual worker 2,Trailer_60,PACK_(VERP_P)_Location,2064,2026-09-11 10:24:00
800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Machine Setup,1215,[2026-09-11 10:45:00-2026-09-11 10:46:00],1~17,Operator 1,PACK_(VERP_P),PACK_(VERP_P)_Location,2086,2026-09-11 10:46:00
835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Machine Loading,1248,[2026-09-11 13:31:00-2026-09-11 13:32:00],1~17,Manual worker 1,PACK_(VERP_P),PACK_(VERP_P)_Location,2252,2026-09-11 13:32:00
847,__export__.mrp_production_6300_645dbbde,[4022-637-29301] Hinge Block Fixed RM,14964.0,17.0,2026-01-16 10:00:00,TBRM /MO/01266-002,PACK - Packaging (VERP_P),__export__.mrp_workcenter_67_d1ac8ce6,PACK_(VERP_P),Packaging (VERP_P),...,NaN,Machine Processing,1289,[2026-09-11 13:32:00-2026-09-11 13:47:00],1~17,PACK_(VERP_P),PACK_(VERP_P),PACK_(VERP_P)_Location,2267,2026-09-11 13:47:00
873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Machine Unloading,1305,[2026-09-11 14:39:00-2026-09-11 14:40:00],1~17,Manual worker 1,PACK_(VERP_P),PACK_(VERP_P)_Location,2320,2026-09-11 14:40:00
886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,1335,[2026-09-11 14:58:00-2026-09-11 14:59:00],1~17,Manual worker 1,Trailer_60,PACK_(VERP_P)_Location,2339,2026-09-11 14:59:00
887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,1350,[2026-09-11 14:59:00-2026-09-11 15:00:00],1~17,Manual worker 1,Trailer_60,Trailer_60,2340,2026-09-11 15:00:00
888,__export__.mrp_production_6300_645dbbde,[4022-637-29301] Hinge Block Fixed RM,14964.0,17.0,2026-01-16 10:00:00,TBRM /MO/01266-002,Central Inventory,Central Inventory Input,NaN,-,...,238.0,Trailer Unloading,1351,[2026-09-11 15:00:00-2026-09-11 15:01:00],1~17,Manual worker 1,Trailer_60,CentralBuffer_Location,2341,2026-09-11 15:01:00

______________________________

,ID,Product,Product/ID,Quantity To Produce,Deadline,Reference,Work Orders/Work Center,Work Orders/Work Center/ID,Processing Machine,Work Orders/Operation,...,Lateness (days),EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,1,[2026-09-10 08:00:00-2026-09-10 08:01:00],1~17,Operator 1,Trailer_60,CentralBuffer_Location,481,2026-09-10 08:01:00
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,154,[2026-09-10 08:01:00-2026-09-10 08:02:00],1~17,Operator 1,Trailer_60,Trailer_60,482,2026-09-10 08:02:00
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,158,[2026-09-10 08:02:00-2026-09-10 08:03:00],1~17,Operator 1,Trailer_60,BW_(BKW_01)_Location,483,2026-09-10 08:03:00
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Operator Move,166,[2026-09-10 08:04:00-2026-09-10 08:05:00],-,Operator 1,-,CentralBuffer_Location,485,2026-09-10 08:05:00
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,5,[2026-09-10 08:05:00-2026-09-10 08:06:00],168~259,Operator 1,Trailer_64,CentralBuffer_Location,486,2026-09-10 08:06:00
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,181,[2026-09-10 08:06:00-2026-09-10 08:07:00],168~259,Operator 1,Trailer_64,Trailer_64,487,2026-09-10 08:07:00
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,185,[2026-09-10 08:07:00-2026-09-10 08:08:00],168~259,Operator 1,Trailer_64,BW_(BKW_01)_Location,488,2026-09-10 08:08:00
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Operator Move,191,[2026-09-10 08:09:00-2026-09-10 08:10:00],-,Operator 1,-,OUT - Outsourced activity_(OUT - Outsourced)_L...,490,2026-09-10 08:10:00
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,190,[2026-09-10 08:10:00-2026-09-10 08:11:00],-,Operator 1,Trailer_63,CentralBuffer_Location,491,2026-09-10 08:11:00
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,9,[2026-09-10 08:11:00-2026-09-10 08:12:00],1430~1953,Operator 1,Trailer_63,CentralBuffer_Location,492,2026-09-10 08:12:00
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,209,[2026-09-10 08:12:00-2026-09-10 08:13:00],1430~1953,Operator 1,Trailer_63,Trailer_63,493,2026-09-10 08:13:00
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,213,[2026-09-10 08:13:00-2026-09-10 08:14:00],1430~1953,Operator 1,Trailer_63,M3-02_(FR3_02)_Location,494,2026-09-10 08:14:00
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Operator Move,219,[2026-09-10 08:15:00-2026-09-10 08:16:00],-,Operator 1,-,MP3_(UITG_M)_Location,496,2026-09-10 08:16:00
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,218,[2026-09-10 08:16:00-2026-09-10 08:17:00],-,Operator 1,Trailer_60,CentralBuffer_Location,497,2026-09-10 08:17:00
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,13,[2026-09-10 08:17:00-2026-09-10 08:18:00],3236~3324,Operator 1,Trailer_60,CentralBuffer_Location,498,2026-09-10 08:18:00
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,234,[2026-09-10 08:18:00-2026-09-10 08:19:00],3236~3324,Operator 1,Trailer_60,Trailer_60,499,2026-09-10 08:19:00
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,238,[2026-09-10 08:19:00-2026-09-10 08:20:00],3236~3324,Operator 1,Trailer_60,BW_(BKW_01)_Location,500,2026-09-10 08:20:00
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,247,[2026-09-10 08:21:00-2026-09-10 08:22:00],-,Operator 1,Trailer_60,CentralBuffer_Location,502,2026-09-10 08:22:00
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,19,[2026-09-10 08:22:00-2026-09-10 08:23:00],3630~3653,Operator 1,Trailer_60,CentralBuffer_Location,503,2026-09-10 08:23:00
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,255,[2026-09-10 08:23:00-2026-09-10 08:24:00],3630~3653,Operator 1,Trailer_60,Trailer_60,504,2026-09-10 08:24:00

,ID,Product,Product/ID,Quantity To Produce,Deadline,Reference,Work Orders/Work Center,Work Orders/Work Center/ID,Processing Machine,Work Orders/Operation,...,Lateness (days),EventName,EventID,ProgressSteps,Items,Resource,Equipment,Location,SimTime,Date
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,2,[2026-09-10 08:00:00-2026-09-10 08:01:00],18~63,Operator 2,Trailer_61,CentralBuffer_Location,481,2026-09-10 08:01:00
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,155,[2026-09-10 08:01:00-2026-09-10 08:02:00],18~63,Operator 2,Trailer_61,Trailer_61,482,2026-09-10 08:02:00
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,159,[2026-09-10 08:02:00-2026-09-10 08:03:00],18~63,Operator 2,Trailer_61,OUT - Outsourced activity_(OUT - Outsourced)_L...,483,2026-09-10 08:03:00
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Operator Move,170,[2026-09-10 08:04:00-2026-09-10 08:05:00],-,Operator 2,-,BW_(BKW_01)_Location,485,2026-09-10 08:05:00
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,169,[2026-09-10 08:05:00-2026-09-10 08:06:00],-,Operator 2,Trailer_60,CentralBuffer_Location,486,2026-09-10 08:06:00
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,6,[2026-09-10 08:06:00-2026-09-10 08:07:00],260~875,Operator 2,Trailer_60,CentralBuffer_Location,487,2026-09-10 08:07:00
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,182,[2026-09-10 08:07:00-2026-09-10 08:08:00],260~875,Operator 2,Trailer_60,Trailer_60,488,2026-09-10 08:08:00
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,186,[2026-09-10 08:08:00-2026-09-10 08:09:00],260~875,Operator 2,Trailer_60,M3-01_(FR3_01)_Location,489,2026-09-10 08:09:00
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,197,[2026-09-10 08:10:00-2026-09-10 08:11:00],-,Operator 2,Trailer_60,CentralBuffer_Location,491,2026-09-10 08:11:00
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,10,[2026-09-10 08:11:00-2026-09-10 08:12:00],1954~2653,Operator 2,Trailer_60,CentralBuffer_Location,492,2026-09-10 08:12:00
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,206,[2026-09-10 08:12:00-2026-09-10 08:13:00],1954~2653,Operator 2,Trailer_60,Trailer_60,493,2026-09-10 08:13:00
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,210,[2026-09-10 08:13:00-2026-09-10 08:14:00],1954~2653,Operator 2,Trailer_60,MP3_(UITG_M)_Location,494,2026-09-10 08:14:00
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Operator Move,223,[2026-09-10 08:15:00-2026-09-10 08:16:00],-,Operator 2,-,OUT - Outsourced activity_(OUT - Outsourced)_L...,496,2026-09-10 08:16:00
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,222,[2026-09-10 08:16:00-2026-09-10 08:17:00],-,Operator 2,Trailer_61,CentralBuffer_Location,497,2026-09-10 08:17:00
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,14,[2026-09-10 08:17:00-2026-09-10 08:18:00],3325~3564,Operator 2,Trailer_61,CentralBuffer_Location,498,2026-09-10 08:18:00
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,235,[2026-09-10 08:18:00-2026-09-10 08:19:00],3325~3564,Operator 2,Trailer_61,Trailer_61,499,2026-09-10 08:19:00
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Unloading,239,[2026-09-10 08:19:00-2026-09-10 08:20:00],3325~3564,Operator 2,Trailer_61,M4-02_(FR4_02)_Location,500,2026-09-10 08:20:00
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Bring Equipment,250,[2026-09-10 08:21:00-2026-09-10 08:22:00],-,Operator 2,Trailer_61,CentralBuffer_Location,502,2026-09-10 08:22:00
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Loading,20,[2026-09-10 08:22:00-2026-09-10 08:23:00],3654~4013,Operator 2,Trailer_61,CentralBuffer_Location,503,2026-09-10 08:23:00
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,...,NaN,Trailer Transport,256,[2026-09-10 08:23:00-2026-09-10 08:24:00],3654~4013,Operator 2,Trailer_61,Trailer_61,504,2026-09-10 08:24:00

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

diagnose = True

print("Item batches: "+str(len(exec_df["Items"].unique())))

for batch in exec_df["Items"].unique():
    if pd.isnull(batch):
        continue
    sub_df = exec_df[exec_df["Items"] == batch]
    sub_df = sub_df.sort_values(['SimTime'])
    start = sub_df.iloc[0, sub_df.columns.get_loc('Location')]
    end = sub_df.iloc[len(sub_df)-1, sub_df.columns.get_loc('Location')]

    if batch !="1~17":
        display(sub_df)
    
        print("______________________________")
    

#process_df = exec_df[exec_df["EventName"] == "Machine Processing"]

for myloc in exec_df["Location"].unique():
    print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    print("Location: ",myloc)
    sub_df = exec_df[exec_df["Location"] == myloc]
    sub_df  = sub_df[(sub_df["EventName"] == "Machine Setup") | (sub_df["EventName"] =="Machine Loading") | (sub_df["EventName"] == "Machine Processing") | (sub_df["EventName"] == "Machine Unloading")]
    if diagnose and len(sub_df)  > 0:
        for i,r in sub_df.iterrows():
            print(r["EventName"],r["EventID"],r["Location"],r["SimTime"])
        
        #display(sub_df)

    


print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "BufferData.csv"))

for buff in exec_df["BufferName"].unique():
    sub_df = exec_df[exec_df["BufferName"] == buff]
    agg_df = sub_df.groupby(['BufferName','Time'])['No.Items'].max().reset_index()
    agg_df = agg_df.rename(columns={agg_df.columns[-1]: "No.Items"})

    if buff in ["Central_Output","Central_Input"]:
        sns.barplot(agg_df, x="Time", y="No.Items", legend=False).set_title(buff)
        plt.xticks(rotation=45)
        plt.show()
        
        display(agg_df.head(100))
        print("______________________________")

In [ ]:
import pandas as pd

location_df = pd.read_csv(os.path.join("..", "data", "simulation", "LocationData.csv"))

for entity in location_df["EntityID"].unique():
    sub_df = location_df[location_df["EntityID"] == entity]
    display(sub_df)
    print("______________________________")

In [ ]:
# Importing the matplotlib.pyplot
import matplotlib.pyplot as plt

# Declaring a figure "gnt"
fig, gnt = plt.subplots()

# Setting Y-axis limits
gnt.set_ylim(0, 50)

# Setting X-axis limits
gnt.set_xlim(0, 160)

# Setting labels for x-axis and y-axis
gnt.set_xlabel('seconds since start')
gnt.set_ylabel('Processor')

# Setting ticks on y-axis
gnt.set_yticks([15, 25, 35])
# Labelling tickes of y-axis
gnt.set_yticklabels(['1', '2', '3'])

# Setting graph attribute
gnt.grid(True)

# Declaring a bar in schedule
gnt.broken_barh([(40, 50)], (30, 9), facecolors =('tab:orange'))

# Declaring multiple bars in at same level and same width
gnt.broken_barh([(110, 10), (150, 10)], (10, 9),
                         facecolors ='tab:blue')

gnt.broken_barh([(10, 50), (100, 20), (130, 10)], (20, 9),
                                  facecolors =('tab:red'))

In [ ]:
import pandas as pd

exec_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

demands_df = exec_df.groupby(['Items','ID','Product','Work Orders/Operation','EventName','EventID','Resource','Date'])['SimTime'].agg(lambda x:list(x)).reset_index()

for demand in demands_df['ID'].unique():
    demand_df = demands_df[demands_df["ID"] == demand]
    demand_df['Date']  = pd.to_datetime(demand_df['Date'], format="%Y-%m-%d %H:%M:%S")
    display(demand_df)

In [ ]:
import pandas as pd 

milp_schedule_df = pd.read_csv(os.path.join("..", "data", "schedules", "TBRM_Plan_2026-08-19_R10_2026-09-01.csv"))

sim_schedule_df = pd.read_csv(os.path.join("..", "data", "simulation", "EventExecutionData.csv"))

sim_schedule_df = sim_schedule_df[["ID","Product","Product/ID","Quantity To Produce","Deadline","Reference","Work Orders/Work Center","Work Orders/Work Center/ID","Work Orders/Operation","Operation Order","Work Orders/Expected Duration","Work Orders/Start(SIM)","Work Orders/End(SIM)","Work Orders/Status(SIM)","Tardy(SIM)","Lateness (days)(SIM)"]]

schedule_df = pd.merge(milp_schedule_df, sim_schedule_df,  how="left", on=["ID","Product","Product/ID","Quantity To Produce","Deadline","Reference","Work Orders/Work Center","Work Orders/Work Center/ID","Work Orders/Operation","Operation Order","Work Orders/Expected Duration"])

schedule_df.to_csv(os.path.join("..", "data", "schedules", "Combined_Schedule.csv"),index = False)

In [ ]:
"""
             
            for j in EDDordered:
                for altmach in j.getOperation().getAlternativeResources():
                    if altmach.getName()== "OUT - Outsourced activity_(OUT - Outsourced)":
                        #schedule right here!
                        mymach = self.getMachineDict()[altmach]

                        jobest = j.getEarliestStart(self.getSchedulableJobs())

                    
                        shiftind = 0
                        currentshift = mymach.getMyShifts()[shiftind]

                        while currentshift.getEndTime() < jobest:
                            shiftind+=1
                            if shiftind >= len(mymach.getMyShifts())
                                currentshift = None
                                break
                            currentshift = mymach.getMyShifts()[shiftind]

                        startshift = currentshift 
                        

                        
                        if currentshift != None:
                            
                            process_start = max(jobest,currentshift.getStartTime())
                            
                            slotstart = currentshift.getStartTime()
                            timelength = mymach.getTimeLength(slotstart,mymach.getMyShifts()[-1].getEndTime())

                            if timelength >= j.getProcessTime():

                                currentslotshifts = []
        
                                currenttime = process_start
                                procss_shft_strt = currenttime
                                proctime = j.getProcessTime()
                                currentslotshifts.append(currentshift) 

                                if proctime <= currentshift.getEndTime() - procss_shft_strt: 
                                    currenttime = procss_shft_strt+proctime
                                    proctime = 0 
                                else:
                                    currenttime = currentshift.getEndTime()+1
                                    proctime -= (currentshift.getEndTime()+1 - procss_shft_strt)

                                
                                shftind = mymach.getMyShifts().index(currentshift)
                                    
                                while (shftind < len(mymach.getMyShifts())) & proctime > 0:
                                    shftind+=1
                                    if (shftind < len(mymach.getMyShifts())):
                                        currentshift = mymach.getMyShifts()[shftind]
                                        currentslotshifts.append(currentshift)
                                        procss_shft_strt = currentshift.getStartTime()
                                    if proctime <= currentshift.getEndTime() - procss_shft_strt:
                                        currenttime = procss_shft_strt+proctime
                                        proctime = 0 
                                    else:
                                        currenttime = currentshift.getEndTime()+1
                                        proctime -= (currentshift.getEndTime()+1 - procss_shft_strt)

                                j.getOperation().setStart(self.convertSimTimeToDate(process_start))
                                j.getOperation().setCompletion(self.convertSimTimeToDate(currenttime))
                               
                                j.getOperation().setProcessMachine(altmach)
                                mymach.getSchedule().append(((startshift,process_start),(currentshift,currenttime)))
                                mymach.getJobStarts().append((j,process_start))
        
                                j.setStart(process_start)
                                j.setCompletion(currenttime)
                                j.setScheduled()

                                
            """"                     
   """
            for job in self.getSchedulableJobs():
                
                for mymatch in job.getMyMatches():
                    #progress.value+= "Match ("+str(mymatch.getJob().getProduct().getPN())+"):  "+str(mymatch.getStart())+"-"+str(mymatch.getCompletion())+", mach: "+str(mymatch.getMachine().getMachine().getName())+"\n"
                    if mymatch.getMILPVar().solution_value() > 0.5:
                        progress.value+= "Scheduled Job("+str(mymatch.getJob().getProduct().getPN())+"):  "+str(mymatch.getStart())+"-"+str(mymatch.getCompletion())+", mach: "+str(mymatch.getMachine().getMachine().getName())+"\n"
                        succ = job.getSuccessortoSchedule()
                        if succ!= None:
                            for succmatch in succ.getMyMatches():
                                #progress.value+= ">> SuccMatch "+str(succmatch.getJob().getProduct().getPN())+"):  "+str(succmatch.getStart())+"-"+str(succmatch.getCompletion())+", mach: "+str(succmatch.getMachine().getMachine().getName())+"\n"
                                if succmatch.getMILPVar().solution_value() > 0.5:
                                     progress.value+= ">> Successor Job("+str(succmatch.getJob().getProduct().getPN())+"):  "+str(succmatch.getStart())+"-"+str(succmatch.getCompletion())+", mach: "+str(succmatch.getMachine().getMachine().getName())+"\n"
                            succ_succ = succ.getSuccessortoSchedule()
                            if succ_succ != None:
                                for succ_succ_match in succ_succ.getMyMatches():
                                    #progress.value+= ">> Succ-Succ Match "+str(succ_succ_match.getJob().getProduct().getPN())+"):  "+str(succ_succ_match.getStart())+"-"+str(succ_succ_match.getCompletion())+", mach: "+str(succ_succ_match.getMachine().getMachine().getName())+"\n"
                                    if succ_succ_match.getMILPVar().solution_value() > 0.5:
                                        progress.value+= ">> Successor-Successor Job("+str(succ_succ_match.getJob().getProduct().getPN())+"):  "+str(succ_succ_match.getStart())+"-"+str(succ_succ_match.getCompletion())+", mach: "+str(succ_succ_match.getMachine().getMachine().getName())+"\n"
            """